# Generated by Django 2.0.1 on 2018-02-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20180216_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='pictures',
            field=models.ManyToManyField(blank=True, null=True, to='image.Picture', verbose_name='相册图片'),
        ),
    ]
