# Generated by Django 2.0.1 on 2018-02-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20180216_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, '多相册'), (2, '单相册')], default=1, verbose_name='相册类型'),
        ),
    ]
