# Generated by Django 2.0.1 on 2018-02-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_auto_20180217_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-add_date',)},
        ),
        migrations.AlterModelOptions(
            name='favoritealbum',
            options={'ordering': ('-add_date',)},
        ),
    ]
