# Generated by Django 2.0.1 on 2018-02-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackuser',
            name='mark',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='followuser',
            name='mark',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='备注'),
        ),
    ]
