# Generated by Django 2.0.1 on 2018-01-28 04:03

from django.db import migrations, models
import utils.uauth_utils


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='latest_albums',
            field=models.CharField(default='我的相册', max_length=16, verbose_name='最近操作的albums'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to=utils.uauth_utils.avatar_upload_path, verbose_name='头像'),
        ),
    ]
