# Generated by Django 2.0.1 on 2018-01-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0002_auto_20180128_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='123abc@163.com', max_length=254, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
