# Generated by Django 2.0.1 on 2018-02-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0003_userinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='im_token',
            field=models.CharField(default='aaa', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_hash',
            field=models.CharField(max_length=40),
        ),
    ]
