# Generated by Django 2.0.1 on 2018-02-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0005_auto_20180203_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='im_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
